import { TableColumnProperties } from 'exceljs';

export const ippSheetColumns = [
  { header: 'vevo-0', key: 'vevo-0', width: 10 },
  { header: 'Iktatószám', key: 'key', width: 32 },
  { header: 'Vevő neve', key: 'name', width: 32 },
  { header: '', key: 'empty1', width: 2 },
  { header: '', key: 'mainGroup', width: 18 },
  { header: '', key: 'secondaryGroup', width: 2 },
  { header: 'Irányítószám', key: 'postalCode', width: 10 },
  { header: 'Település', key: 'city', width: 14 },
  { header: 'Közterület neve', key: 'street', width: 14 },
  { header: 'Ország', key: 'country', width: 14 },
  { header: '', key: 'empty2', width: 2 },
  { header: '', key: 'empty3', width: 2 },

  { header: 'Irányítószám', key: 'postalCode1', width: 10 },
  { header: 'Település', key: 'city1', width: 14 },
  { header: 'Közterület neve', key: 'street1', width: 14 },
  { header: 'Ország', key: 'country1', width: 14 },

  { header: '', key: 'empty4', width: 2 },
  { header: '', key: 'empty5', width: 2 },
  { header: '', key: 'empty6', width: 2 },
  { header: '', key: 'empty7', width: 2 },
  { header: '', key: 'empty8', width: 2 },
  { header: '', key: 'empty9', width: 2 },
  { header: '', key: 'empty10', width: 2 },
  { header: '', key: 'empty11', width: 2 },

  { header: '', key: 'cashOnly', width: 6 },

  { header: '', key: 'empty12', width: 2 },
  { header: '', key: 'empty13', width: 2 },
  { header: '', key: 'empty14', width: 2 },

  { header: 'Adószám', key: 'taxNumber', width: 18 },

  { header: '', key: 'empty14', width: 2 },
  { header: '', key: 'empty15', width: 2 },
  { header: '', key: 'empty16', width: 2 },
  { header: '', key: 'empty17', width: 2 },
  { header: '', key: 'empty18', width: 2 },
  { header: '', key: 'empty19', width: 2 },
  { header: '', key: 'empty20', width: 2 },
  { header: '', key: 'empty21', width: 2 },
  { header: '', key: 'empty22', width: 2 },
  { header: '', key: 'empty23', width: 2 },
  { header: '', key: 'empty24', width: 2 },
  { header: '', key: 'empty25', width: 2 },

  { header: 'Mozgásirány', key: 'direction', width: 4 },

  { header: '', key: 'empty25', width: 2 },
  { header: '', key: 'empty26', width: 2 },
  { header: '', key: 'empty27', width: 2 },
  { header: '', key: 'empty28', width: 2 },
  { header: '', key: 'empty29', width: 2 },
  { header: '', key: 'empty30', width: 2 },
  { header: '', key: 'empty31', width: 2 },
  { header: '', key: 'empty32', width: 2 },
  { header: '', key: 'empty33', width: 2 },
  { header: '', key: 'empty34', width: 2 },
  { header: '', key: 'empty35', width: 2 },
  { header: '', key: 'empty36', width: 2 },
  { header: '', key: 'empty37', width: 2 },
  { header: '', key: 'empty38', width: 2 },
  { header: '', key: 'empty39', width: 2 },
  { header: '', key: 'empty40', width: 2 },

  { header: 'Közterület neve', key: 'street2', width: 14 },
  { header: 'Közterület jellege', key: 'streetType', width: 14 },
  { header: 'Házszám', key: 'address', width: 14 },

  { header: '', key: 'empty41', width: 2 },
  { header: '', key: 'empty42', width: 2 },
  { header: '', key: 'empty43', width: 2 },
  { header: '', key: 'empty44', width: 2 },
  { header: '', key: 'empty45', width: 2 },

  { header: 'Közterület neve', key: 'street3', width: 14 },
  { header: 'Közterület jellege', key: 'streetType1', width: 14 },
  { header: 'Házszám', key: 'address1', width: 14 },

  { header: '', key: 'empty46', width: 2 },
  { header: '', key: 'empty47', width: 2 },
  { header: '', key: 'empty48', width: 2 },
  { header: '', key: 'empty49', width: 2 },
  { header: '', key: 'empty50', width: 2 },
  { header: '', key: 'empty51', width: 2 },

  { header: 'Ügyviteli kategória', key: 'category', width: 2 },
] as const;

export const deepPartnerTableColumns: readonly TableColumnProperties[] = [
  { name: 'Sorszám' },
  { name: 'Partner típus' },
  { name: 'Partner kereskedelmi típus' },
  { name: 'Iktatószám' },
  { name: 'Megnevezés' },
  { name: 'Külső iktatószám' },
  { name: 'Elemző iktatószám' },
  { name: 'Külső azonosító' },
  { name: 'Számlázási cím.Ország' },
  { name: 'Számlázási cím.Megye' },
  { name: 'Számlázási cím.Irányítószám' },
  { name: 'Számlázási cím.Város' },
  { name: 'Számlázási cím.Kerület' },
  { name: 'Számlázási cím.Közterület jellege' },
  { name: 'Számlázási cím.Közterület' },
  { name: 'Számlázási cím.Házszám' },
  { name: 'Számlázási cím.Épület' },
  { name: 'Számlázási cím.Lépcsőház' },
  { name: 'Számlázási cím.Emelet' },
  { name: 'Számlázási cím.Ajtó' },
  { name: 'Számlázási cím.Postafiók' },
  { name: 'Számlázási cím.Cím' },
  { name: 'Számlázási cím.Telefon' },
  { name: 'Számlázási cím.Mobil' },
  { name: 'Számlázási cím.Fax' },
  { name: 'Számlázási cím.Email' },
  { name: 'Számlázási cím.Honlap' },
  { name: 'Számlázási cím.Skype-név' },
  { name: 'Postacím.Ország' },
  { name: 'Postacím.Megye' },
  { name: 'Postacím.Irányítószám' },
  { name: 'Postacím.Város' },
  { name: 'Postacím.Kerület' },
  { name: 'Postacím.Közterület jellege' },
  { name: 'Postacím.Közterület' },
  { name: 'Postacím.Házszám' },
  { name: 'Postacím.Épület' },
  { name: 'Postacím.Lépcsőház' },
  { name: 'Postacím.Emelet' },
  { name: 'Postacím.Ajtó' },
  { name: 'Postacím.Postafiók' },
  { name: 'Postacím.Cím' },
  { name: 'Postacím.Telefon' },
  { name: 'Postacím.Mobil' },
  { name: 'Postacím.Fax' },
  { name: 'Postacím.Email' },
  { name: 'Postacím.Honlap' },
  { name: 'Postacím.Skype-név' },
  { name: 'Web áruházban látható' },
  { name: 'Üzletkötő' },
  { name: 'Devizanem' },
  { name: 'Nyelv' },
  { name: 'Nyilvántartási kódunk  a  partnernél' },
  { name: 'Adószám' },
  { name: 'Partner üzleti kategória' },
  { name: 'Csoportos adó alanyisági tag' },
  { name: 'Csoportos adóazonosító szám' },
  { name: 'Közösségi csoportos adóazonosító szám' },
  { name: 'Közösségi adószám' },
  { name: 'Közösségi tagállam kód' },
  { name: 'Vállalkozói igazolványszám' },
  { name: 'Működési engedély szám' },
  { name: 'Egyéb igazolvány szám' },
  { name: 'VPID szám' },
  { name: 'GLN szám' },
  { name: 'Pénzforgalmi áfa' },
  { name: 'Feladó/Rendeltetési tagállam' },
  { name: 'Partner ügyviteli kategória' },
  { name: 'Általános ügyviteli kategória' },
  { name: 'Bizományos készlet raktár' },
  { name: 'Dolgozói készlet raktár' },
  { name: 'Hitelkeret ellenőrzési szabály' },
  { name: 'Hitelkeret (alap devizában)' },
  { name: 'MRP generálás rendelésenként' },
  { name: 'Aktív' },
  { name: 'EORI szám' },
  { name: 'Jövedéki típus' },
  { name: 'Jövedéki mentesítés igazolás száma' },
  { name: 'Telephely adóraktári engedélyszám' },
  { name: 'Kereskedő adóraktári engedélyszám' },
  { name: 'Jövedéki engedélyszám' },
  { name: 'Felhasználói engedélyszám' },
  { name: 'Nyilvántartásba vett felhasználói engedélyszám' },
  { name: 'Bejegyzett kereskedői engedélyszám' },
  { name: 'Eseti bejegyzett kereskedői engedélyszám' },
  { name: 'Igazolt címzett engedélyszám' },
  { name: 'Eseti igazolt címzett engedélyszám' },
  { name: 'Vámhivatal' },
  { name: 'Fej dimenzió.Fej dimenzió 01' },
  { name: 'Fej dimenzió.Fej dimenzió 02' },
  { name: 'Fej dimenzió.Fej dimenzió 03' },
  { name: 'Fej dimenzió.Fej dimenzió 04' },
  { name: 'Fej dimenzió.Fej dimenzió 05' },
  { name: 'Fej dimenzió.Fej dimenzió 06' },
  { name: 'Fej dimenzió.Fej dimenzió 07' },
  { name: 'Fej dimenzió.Fej dimenzió 08' },
  { name: 'Fej dimenzió.Fej dimenzió 09' },
  { name: 'Fej dimenzió.Fej dimenzió 10' },
  { name: 'Sor dimenzió.Sor dimenzió 01' },
  { name: 'Sor dimenzió.Sor dimenzió 02' },
  { name: 'Sor dimenzió.Sor dimenzió 03' },
  { name: 'Sor dimenzió.Sor dimenzió 04' },
  { name: 'Sor dimenzió.Sor dimenzió 05' },
  { name: 'Sor dimenzió.Sor dimenzió 06' },
  { name: 'Sor dimenzió.Sor dimenzió 07' },
  { name: 'Sor dimenzió.Sor dimenzió 08' },
  { name: 'Sor dimenzió.Sor dimenzió 09' },
  { name: 'Sor dimenzió.Sor dimenzió 10' },
  { name: 'Extra adat alap.Szöveges extra 1' },
  { name: 'Extra adat alap.Szöveges extra 2' },
  { name: 'Extra adat alap.Szöveges extra 3' },
  { name: 'Extra adat alap.Szöveges extra 4' },
  { name: 'Extra adat alap.Szöveges extra 5' },
  { name: 'Extra adat alap.Szöveges extra 6' },
  { name: 'Extra adat alap.Szöveges extra 7' },
  { name: 'Extra adat alap.Szöveges extra 8' },
  { name: 'Extra adat alap.Szöveges extra 9' },
  { name: 'Extra adat alap.Szöveges extra 10' },
  { name: 'Extra adat alap.Szám extra 1' },
  { name: 'Extra adat alap.Szám extra 2' },
  { name: 'Extra adat alap.Szám extra 3' },
  { name: 'Extra adat alap.Szám extra 4' },
  { name: 'Extra adat alap.Szám extra 5' },
  { name: 'Extra adat alap.Szám extra 6' },
  { name: 'Extra adat alap.Szám extra 7' },
  { name: 'Extra adat alap.Szám extra 8' },
  { name: 'Extra adat alap.Szám extra 9' },
  { name: 'Extra adat alap.Szám extra 10' },
  { name: 'Extra adat alap.Dátum extra 1' },
  { name: 'Extra adat alap.Dátum extra 2' },
  { name: 'Extra adat alap.Dátum extra 3' },
  { name: 'Extra adat alap.Dátum extra 4' },
  { name: 'Extra adat alap.Dátum extra 5' },
  { name: 'Extra adat alap.Dátum extra 6' },
  { name: 'Extra adat alap.Dátum extra 7' },
  { name: 'Extra adat alap.Dátum extra 8' },
  { name: 'Extra adat alap.Dátum extra 9' },
  { name: 'Extra adat alap.Dátum extra 10' },
  { name: 'Extra adat alap.Logikai extra 1' },
  { name: 'Extra adat alap.Logikai extra 2' },
  { name: 'Extra adat alap.Logikai extra 3' },
  { name: 'Extra adat alap.Logikai extra 4' },
  { name: 'Extra adat alap.Logikai extra 5' },
  { name: 'Extra adat alap.Logikai extra 6' },
  { name: 'Extra adat alap.Logikai extra 7' },
  { name: 'Extra adat alap.Logikai extra 8' },
  { name: 'Extra adat alap.Logikai extra 9' },
  { name: 'Extra adat alap.Logikai extra 10' },
  { name: 'Fizetési mód' },
  { name: 'Kereskedelmi terv partner csoport' },
  { name: 'Fizetés eltolási napok száma' },
  { name: 'Partner vevő csoport 1' },
  { name: 'Partner vevő csoport 2' },
  { name: 'Partner vevő csoport 3' },
  { name: 'Partner szállító csoport 1' },
  { name: 'Partner szállító csoport 2' },
  { name: 'Partner szállító csoport 3' },
  { name: 'Partner kedvezmény csoport' },
  { name: 'Partner ár csoport' },
  { name: 'Cikk ár típus' },
  { name: 'Cikk ár típus - bruttó' },
  { name: 'Minimál cikk ár típus' },
  { name: 'Minimál cikk ár típus - bruttó' },
  { name: 'Cikk ár típus - szerviz' },
  { name: 'Kiskereskedelmi cikk ár típus' },
  { name: 'Cikk kedvezmény típus' },
  { name: 'Cikk kedvezmény típus - bruttó' },
  { name: 'Cikk kedvezmény típus - szerviz' },
  { name: 'Kiskereskedelmi cikk kedvezmény típus' },
  { name: 'Késedelmi kamat típus' },
  { name: 'E-számla' },
  { name: 'E-számla típus' },
  { name: 'E-számla küldése telephelynek is' },
  { name: 'Fizető partner' },
  { name: 'E-számla küldése kapcsolattartónak is' },
  { name: 'Termékdíj ügyviteli kategória - nyilatkozat/átvállalás' },
  { name: 'Termékdíj nyilatkozat/átvállalás hivatkozási szám' },
  { name: 'Partneri cikkadatok használata számlán' },
  { name: 'Iparág kód' },
  { name: 'Alapértelmezett raktár' },
  { name: 'Alapértelmezett tárhely' },
  { name: 'Telephelyenkénti bizonylatolás' },
  { name: 'Járat kategória' },
  { name: 'Marketing kapcsolat' },
  { name: 'Kintlévőség kezelés - Értesítési kör' },
  { name: 'Kintlévőség kezelés - Értesítési típus' },
  { name: 'Kintlévőség kezelés - Értesítési csatorna' },
  { name: 'Partner mint cég' },
];
